### ISSUE TITLE
Unify libboost version? (on 1.55.0)

### ISSUE THREAD

**Issue by allentiak** [EvolutionRTS/Evolution-RTS#107]
While (unsuccessfully) trying to run the game under Debian, I noticed there are modules requiring different libboost versions.
For instance, whereas `libboost-filesystem`, `libboost-thread` and `libboost-system` all use version 1.55.0, `libboost-iostreams` uses version 1.46.1...

Whereas I managed to install version 1.55.0 of the three library modules, there is no libboost version 1.46.1 in any Debian release: it jumps from 1.42 in release 6.0 (codename "squeeze") to version 1.49 in release 7.0 (codename "wheezy").
Unless I manually package the library, I simply cannot get it as a Debian package...

On the contrary, libboost version 1.55 is present in both the latest stable Debian release (codename "stretch", version 9.0) and a not-so old Ubuntu LTS release (14.04LTS, supported until 2019.04)...

Would you please consider unifying all your boost libraries on version 1.55?

**Comment by ForbodingAngel** [comment]
I don't compile the engine, that is actually done by the buildbot over at the engine repo here: https://github.com/spring/spring Would probably be a good idea to post this there.

Specifically I mostly only "support" ubuntu, simply because there are far too many *nix distros to keep track of and frankly, ubuntu is the easiest to deal with. That said, I'm pretty much at the mercy of the engine developers myself.

**Comment by nyov** [comment]
@allentiak, Debian already has springrts (and springlobby) packaged (which is using v. 1.62 of the boost libraries). You could just configure the game to use that engine version.
It's even the latest version in testing (and I backported it for stretch myself, so that is also possible):
https://packages.debian.org/search?keywords=spring

https://springrts.com/wiki/Debian_install
HTH

**Comment by allentiak** [comment]
Hi, @nyov!

Thanks for the tip! I'll try it and let you know.

Best,
Leandro

>

**Comment by allentiak** [comment]
I installed spring on Debian (a simple `apt install spring`).

When I execute `./welobby` on EvolutionRTS, the games lunches :-)

Closes #107
