### ISSUE TITLE
How to use the release files?

### ISSUE THREAD

**Issue by neoedmund** [EvolutionRTS/Evolution-RTS#132]
New release files are released recently like v17.07
but how to use them?
 I just cannot use them by `EvoRTS-Chobby` or any `spring engine` 
`EvoRTS-Chobby` can run but cannot see any game, replays or any data. no single-player game can be started.

**Comment by ScarylePoo** [comment]
Hey sorry for the ambiguity. The release files are intended to be used with sky lobby or something similar. The easiest way would be to get the sky lobby based package via itch.io
https://forboding-angel.itch.io/evolution-rts

Alternatively, you can use spring lobby or any of the other lobbies. The reason it is not showing up in chobby is probably because whatever version of it you have likely has a game filter built into it.

The engine intended for use is baseline 105, but the latest bar engine will probably work just fine. Evo has quite a focus on co-op multiplayer, but in the last release I made sure that the scavengers AI experience is quite fun.

I highly recommend that you grab it from itch.io. a lot of spring engine defaults will make the game look pretty crappy cause a lot of advanced graphic stuff is disabled by default in the bare engine releases.

Feel free to reopen if need be. You can also join our discord and ping me there if you like. Good luck!

**Comment by neoedmund** [comment]
Thank you for you hints!
I found out engine exit with `Dependent archive "evolution rts music addon v3"  not found`
basically if got the music pack, the game can be run like other springrts games.
So I downloaded the link on itch.io and it worked.
