### ISSUE TITLE
Access Violation - Error: Could not open keybind file LuaUI/Configs/evo_keys.lua for writing

### ISSUE THREAD

**Issue by rainerpl** [EvolutionRTS/Evolution-RTS#19]
Hi,

I finished first time install using Steam ,and game throws this error on launch.
infolog.txt
http://pastebin.com/WZtx8p0X

weblobby.log is basically empty, but contains this line which may be useful
[WARNING] [2016-01-07 14:55:49] Process spring finished with error code -1

**Comment by ForbodingAngel** [comment]
The evo_keys.lua isn't actually used. Your real issue is your graphics card drivers:

[f=0000000] Warning: This stack trace indicates a problem with your graphic card driver. Please try upgrading or downgrading it. Specifically recommended is the latest driver, and one that is as old as your graphic card. Make sure to use a driver removal utility, before installing other drivers.

Thanks!
