### ISSUE TITLE
Game does not start, just hear music

### ISSUE THREAD

**Issue by GoogleFrog** [EvolutionRTS/Evolution-RTS#50]
Things that I did:
 * Click play on steam store page.
 * Click on the EvoRTS desktop icon to play it. I downloaded about a GB of updates and then could launch.
 * Ended up in a skinned SWL.
 * Entered a host hosting the EvoRTS metal planet map. Added two ShardLuas.
 * Did !focestart because the start button would not start the game.
 * Hear music, see nothing else.
 * Task manager shows a spring.exe taking 14% CPU and 530 MB of RAM.
 * Waited for 10 minutes.
 * Halted process.

Some things from C:\Program Files (x86)\Steam\steamapps\common\EvolutionRTS\evo_data
 * [infolog.txt](https://github.com/EvolutionRTS/Evolution-RTS/files/675032/infolog.txt)
 * [loadprogress_cached.txt](https://github.com/EvolutionRTS/Evolution-RTS/files/675033/loadprogress_cached.txt)
 * [springsettings.txt](https://github.com/EvolutionRTS/Evolution-RTS/files/675034/springsettings.txt)

**Comment by ForbodingAngel** [comment]
From a clean, non-dev install, it will work fine. I didn't hear back from you in discord as to how isolation worked for you.

Isolation has not been done before because, frankly it has never been needed. A non-dev won't have his common spring folder cluttered with .sdd that point to git and svn repos.

Svn repos being pointed at from games is especially destructive as most springignore.txt files are only targeting the base .svn folder, not all of the multi-level svn folders. So, if you have and .sdd linked form your games folder (Like BAR), remove it and make sure you kill may games/spring/cache folders and archivecache.

**Comment by GoogleFrog** [comment]
I had a closer look at my infolog.txt. I don't think caching has ever been the issue. I load all gadgets, widgets, etc.. and reach "[f=-000001] Loading Skirmish AIs".

**Comment by db81** [comment]
Probably not it because you hang on loading AIs, but a reference for completeness: https://github.com/springweblobby/swl-qt/issues/16
